// import trimatric from "../../assets/images/project/trimatric.png"
import srijonerhut from "../../assets/images/client/srijonerhut.png"
import dogdash from "../../assets/images/client/dogdash.png"
import squeeder from "../../assets/images/client/squeeder.png"
import satez from "../../assets/images/client/satez.png"
import sounddistric from "../../assets/images/client/sounddistric.png"
import privachef from "../../assets/images/client/privachef.png"
import nadim from "../../assets/images/client/nadim.png"
import trimatric from "../../assets/images/client/trimatric.png"
import uttaran from "../../assets/images/client/uttaran.png"
import artact from "../../assets/images/client/artact.png"
import explore from "../../assets/images/client/explore.png"
import indecor from "../../assets/images/client/indecor.png"
import hrd from "../../assets/images/client/hrd.png"
import health from "../../assets/images/client/healthbangla.png"

const List = [
    {
        id: 1,
        name: "Srijoner Hut",
        title: "Bengali film festival of Dallas",
        category: "Development",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        date: "01-01-2021",
        website: "https://srijonerhut.com/",
        client_name: "John Doe",
        client_feedback: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        tools: "",
        language: "Laravel, PHP, MySQL",
        image: srijonerhut,

    },
    {
        id: 2,
        name: "Artact BD",
        title: "Digital Agency",
        category: "Website",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        date: "01-01-2021",
        website: "https://artactbd.com/",
        client_name: "John Doe",
        client_feedback: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        tools: "",
        language: "HTML, CSS",
        image: artact,

    },
    {
        id: 3,
        name: "Trimatric Architects & Engineers",
        category: "Development",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        date: "01-01-2021",
        website: "https://www.trimatric.com/",
        client_name: "John Doe",
        client_feedback: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        tools: "Figma",
        language: "Laravel, PHP, MySQL",
        image: trimatric,
    },
    {
        id: 4,
        name: "Nadim's Design",
        title: "Personal Portfolio Website",
        category: "Development",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        date: "01-01-2021",
        website: "https://www.nadimsdesign.com/",
        client_name: "Nazmul Nadim",
        client_feedback: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        tools: "Figma",
        language: "Laravel, PHP, MySQL",
        image: nadim,
    },
    {
        id: 5,
        name: "Human Resource Development",
        title: "HR solutions",
        category: "Development",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        date: "01-01-2021",
        website: "https://hrd.com.bd/",
        client_name: "Nazmul Nadim",
        client_feedback: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        tools: "Figma",
        language: "Laravel, PHP, MySQL",
        image: hrd,
    },
    {
        id: 6,
        name: "Health Bangla",
        title: "COVID-19 Helpline for Bangladeshi in USA",
        category: "Website",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        date: "01-01-2021",
        website: "https://healthbangla.org/",
        client_name: "Nazmul Nadim",
        client_feedback: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        tools: "",
        language: "HTML, CSS",
        image: health,
    },
    {
        id: 7,
        name: "Sound District",
        title: "Music",
        category: "Wordpress",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        date: "01-01-2021",
        website: "https://sounddistrict.org/",
        client_name: "Nazmul Nadim",
        client_feedback: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        tools: "",
        language: "HTML, CSS",
        image: sounddistric,
    },
    {
        id: 8,
        name: "Indecor BD",
        title: "Furniture Ecommerce",
        category: "Development",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        date: "01-01-2021",
        website: "https://indecor.com.bd/",
        client_name: "Nazmul Nadim",
        client_feedback: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        tools: "",
        language: "VueJs, Laravel",
        image: indecor,
    },
    {
        id: 8,
        name: "Satez Super Shop",
        title: "Grocery Ecommerce",
        category: "Wordpress",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        date: "01-01-2021",
        website: "https://satez.com.bd/",
        client_name: "Satez BD",
        client_feedback: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        tools: "",
        language: "VueJs, Laravel",
        image: satez,
    },
    {
        id: 9,
        name: "Explore Asian Food",
        title: "Food Blog",
        category: "Wordpress",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        date: "01-01-2021",
        website: "https://exploreasianfood.com/",
        client_name: "Explore Asian Food",
        client_feedback: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        tools: "",
        language: "php, Laravel",
        image: explore,
    },
    {
        id: 10,
        name: "Doge Dash",
        title: "Shopify Ecommerce",
        category: "Shopify",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        date: "01-01-2021",
        website: "https://www.dogedash.com",
        client_name: "Explore Asian Food",
        client_feedback: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        tools: "",
        language: "php, Laravel",
        image: dogdash,
    },
    {
        id: 11,
        name: "PrivaChef",
        title: "UI Design",
        category: "UI",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        date: "01-01-2021",
        website: "https://privachef.com/",
        client_name: "privachef",
        client_feedback: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
        tools: "",
        language: "php, Laravel",
        image: privachef,
    }
]

export default List;